-
  branches:
    only:
      - master
  version: '{build}'
  image: Visual Studio 2017
  environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  configuration: Release
  before_build:
    - ps: dotnet restore
  build:
    publish_nuget: true
    verbosity: minimal
  test_script:
    - ps: dotnet test -c Release --no-build ./unit/Test.csproj
  deploy:
    provider: NuGet
    api_key:
      secure: lDZOfkSGSv+vsyfNqk8CEfIeePGrEr6eNpeu3qDo8DlUFlJnubB+0KuR01t34hVl
  dotnet_csproj:
    patch: false
-
  version: '{build}'
  image: Visual Studio 2017
  environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  configuration: Release
  before_build:
    - ps: dotnet restore
  build:
    publish_nuget: true
    verbosity: minimal
  test_script:
    - ps: dotnet test -c Release --no-build ./unit/Test.csproj
  dotnet_csproj:
    patch: false
