image: microsoft/aspnetcore-build:1.0-1.1

before_script:
  - dotnet restore

stages:
  - build
  - publish

build:
  stage: build
  script:
    - dotnet build -c Release
    - dotnet test --no-build -c Release ./unit/Test.csproj
    - dotnet pack --no-build -c Release -o "$(pwd)/dist/"
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  script: dotnet nuget push dist/*.nupkg -k -k $ARTIFACTORY_USERNAME:$ARTIFACTORY_API_KEY
  dependencies:
    - build
  only:
    - master
