image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine

stages:
- build
- test-pack
- deploy

cache:
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  script:
  - dotnet build -c Release
  artifacts:
    untracked: true

test:
  stage: test-pack
  script:
  - dotnet test -c Release

pack:
  stage: test-pack
  script:
  - dotnet pack --configuration Release --output "$(pwd)/dist/"
  artifacts:
    untracked: false
    paths:
    - ./dist/

deploy:
  stage: deploy
  script:
  - dotnet nuget push ./dist/*.nupkg -k "${NUGET_API_KEY}"
  only:
  - master
