image: microsoft/aspnetcore-build:2.0

stages:
  - build
  - test-pack
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  script:
    - dotnet build -c Release
  artifacts:
    untracked: true

test:
  stage: test-pack
  script:
    - dotnet test --no-build -c Release ./unit/Test.csproj

pack:
  stage: test-pack
  script:
    - dotnet pack --no-build -c Release -o "$(pwd)/dist/"
  artifacts:
    untracked: false
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - dotnet nuget push ./dist/*.nupkg -k $ARTIFACTORY_USERNAME:$ARTIFACTORY_API_KEY
  only:
    - master
